backend:
  # name: test-repo
  name: github
  repo: vicradon/techwinx

media_folder: src/img-uploads
public_folder: /img-uploads

collections:
  - name: Blog-Posts
    label: Blog-Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: last_edit_date, label: Last Edited, widget: datetime }
      - { name: path, label: Path }
      - { name: tags, label: Tags, widget: checkbox, options: ["ai", "mr", "uavs", "tefrica", "vr"]  }
      - { name: templateKey, label: Template Key, widget: select, options: ["blog-template"]}
      - { name: author, label: Author }
      - { name: featuredImage, label: Featured Image }
      - { name: featured, label: Featured,  widget: select, options: [true, false]}
      - { name: category, label: Category, widget: select, options: ["ai", "mr", "uavs", "tefrica"] }
      - { name: category_name, label: Category Name, widget: select, options: ["AI", "MR", "UAVs", "Tefrica"] }
      - { name: body, label: Body, widget: markdown }